### ISSUE TITLE
Error upon opening 

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/IXmapsClient#101]
Get a throw error upon launch, even though usually OK in finding saved profile data. See full terminal transcript below.

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRINUSE 127.0.0.1:2040

Similar (same?) as issue #80.
_________________

Last login: Sat Jan 27 12:47:12 on ttys000
Macintosh-272:~ andrewclementAir$ cd /Applications//IXmapsClient.app/Contents/Resources/ixmaps-darwin/ ; ./start-macos.sh

***************************************************************************
* IXmapsClient local server                                               *
*                                                                         *
* ….
* For more information on IXmapsClient, please visit:                     *
* http://www.ixmaps.ca                                                    *
* https://github.com/ixmaps/IXmapsClient/                                 *
*                                                                         *
***************************************************************************

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:2040
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
Macintosh-272:ixmaps-darwin andrewclementAir$

**Comment by colinmccann** [comment]
This will occur if you have run the client, then closed it by closing the terminal without terminating the node process, then tried running the client again.

You can resolve this by:
- always terminating the node process before closing the terminal
- if you forget, you can terminate the node process with eg kill -9
- you can always restart your comp if all else fails, and this will resolve the issue :)
