### ISSUE TITLE
explore > map re-direction broken?

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/IXmapsClient#104]
The link in a newly generated TR contains the legacy 'explore' instead of 'map', suggesting auto re-direction has broken. 

eg https://www.ixmaps.ca/explore.php?trid=1053970 produces a 404 whereas
     https://www.ixmaps.ca/map.php?trid=1053970 works fine.

**Comment by colinmccann** [comment]
Resolved with 1.1.1 release
