### ISSUE TITLE
Correct Removal instructions in TRgen2 README

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/IXmapsClient#22]
Currently reads:
Removing IXmaps Traceroute Generator

    1) Go to your /Applications folder and delete ixnode folder
    2) Go you to Desktop and delete  IXmapsNode-launcher
	This will completely remove IXmaps Traceroute Generator v. 2.0 from your computer.

Suggest replacing with:

    1) Go to your /Applications folder and delete ixnode APPLICATION
    2) Go TO YOUR Desktop and delete  IXmapsNode-launcher
    3) GO TO ??? AND DELETE THE DMG FILE (OR SOME SUCH)??

	This will completely remove IXmaps Traceroute Generator v. 2.0 from your computer.

**Comment by agamba** [comment]
This is an issue related to Mac OS X, specific to release packaging, in particular to  instructions tin ReadMe files.
