### ISSUE TITLE
Add instructions in TRgen2 README file for adjusting security preferences

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/IXmapsClient#23]
Provide instructions in case of this message:

"ixnode" can't be opened because it is from an identified developer. Your security preferences allow installation of only apps from the Mac App Store and identified developers

**Comment by Andrew-Clement** [comment]
Presumably this can be closed. However main README  for the repo is clearly out of date and I can't find the authoritative source for the README file.  @agamba, please help.

**Comment by agamba** [comment]
I suggest that warnings produced by OS X versioning should be moved somewhere else. This isn't specific to IXmapsClient (per se), but points to app's packaging

**Comment by colinmccann** [comment]
Resolved with IXmapsClient 1.1.1 release
