### ISSUE TITLE
handling submission errors

### ISSUE THREAD

**Issue by vid** [ixmaps/IXmapsClient#3]
the submission json needs a way to indicate different types of errors, such as host not resolved.

**Comment by vid** [comment]
Also, a way to submit platform traces that were terminated due to time.

**Comment by vid** [comment]
Note that right now it sends an 'error' object. in the case of a platform timeout, this will contain:

{ aborted: true}

**Comment by Andrew-Clement** [comment]
Presumably long past, so closing.
