### ISSUE TITLE
Server disconnections - eliminate or reduce greatly.

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/IXmapsClient#55]
When generating TRs I experience frequent server discussions, even with relatively short target lists, and almost always after some delay following the successful completion of a generation run. This is likely to be a serious impediment to users continuing to to generate further TRs. 

The main issue to be resolved is how these disconnections can be eliminated, or at least greatly reduced. The related issue is what to do in the case of disconnection. This is elaborated in the next issue #???

See the accompanying email of Nov 24 for images showing the error messages, with this issue # as sub-title.
What is the cause of it? 
Is it sometimes a timeout? If so, can the time period be greatly lengthened, eg 10 mins.

**Comment by Andrew-Clement** [comment]
I'm still getting server disconnections Issue  https://github.com/ixmaps/ixnode/issues/55

After a fresh re-boot and only FF running (i.e. likely no resource limitations),  no switching of tabs or other apps, and no long pause, the connection was lost in the midst of a pass.  See screenshot and Terminal log below. 

If as it seems likely, it will take some time to fix this elusive bug, please re-word the error message to give more explicit instructions. i.e., instead of: 
     **Server disconnected**
     The server is not responding to ping requests. It may be neccessary to restart it.  
it would read better as:
     **Server disconnected**
     The server is not responding to ping requests and needs to be restarted. Close this window/tab and re-launch from IXmapsClient Command (on your desktop)

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/12848029/11850724/f9c204f8-a3e3-11e5-85b7-d01bbd8baa3a.png)

submitted: Processed www.nus.edu.sg (137.132.21.27) - TRID 91496
STATUS: Host www.unimelb.edu.au
info: now running www.unimelb.edu.au from 11: universities worldwide
info: options{
  "submitter": "AndrewC",
  "postal_code": "V8L",
  "dest": "www.unimelb.edu.au",
  "trset": "11: universities worldwide",
  "queries": 4,
  "timeout": 750,
  "maxhops": 24,
  "raw_protocol": "ICMP",
  "max_sequential_errors": 4,
  "include_platform_traceroute": false,
  "platform_protocol": "Default",
  "platform_limit_ms": 60000,
  "city": "Sidney",
  "isp": "Shaw Communications Inc."
}
hop: {"pass":1,"hop":1,"ttl":1,"ip":"192.168.0.1","rtt":"1.25"}
hop: {"pass":1,"hop":2,"ttl":2,"ip":"0.0.0.0","rtt":"9.26"}
hop: {"pass":1,"hop":3,"ttl":3,"ip":"64.59.162.189","rtt":"15.44"}
hop: {"pass":1,"hop":4,"ttl":4,"ip":"66.163.68.129","rtt":"15.46"}
hop: {"pass":1,"hop":5,"ttl":5,"ip":"66.163.72.242","rtt":"16.53"}
hop: {"pass":1,"hop":6,"ttl":6,"ip":"66.163.74.158","rtt":"18.55"}
hop: {"pass":1,"hop":7,"ttl":7,"ip":"66.163.75.90","rtt":"45.70"}
hop: {"pass":1,"hop":8,"ttl":8,"ip":"206.223.116.227","rtt":"48.40"}
hop: {"pass":1,"hop":9,"ttl":9,"ip":"114.31.199.248","rtt":"192.84"}
hop: {"pass":1,"hop":10,"ttl":10,"ip":"114.31.199.58","rtt":"204.16"}
hop: {"pass":1,"hop":11,"ttl":11,"ip":"114.31.199.28","rtt":"271.10"}
hop: {"pass":1,"hop":12,"ttl":12,"ip":"175.45.72.93","rtt":"194.06"}
hop: {"pass":1,"hop":13,"ttl":13,"ip":"175.45.108.214","rtt":"194.75"}
hop: {"pass":1,"hop":14,"ttl":14,"ip":"124.47.128.22","rtt":"204.37"}
hop: {"pass":1,"hop":15,"ttl":15,"rtt":-1,"err":"timeout"}
hop: {"pass":1,"hop":16,"ttl":16,"rtt":-1,"err":"timeout"}
hop: {"pass":1,"hop":17,"ttl":17,"rtt":-1,"err":"timeout"}
hop: {"pass":1,"hop":18,"ttl":18,"rtt":-1,"err":"timeout"}
maxhops 24
pass: 0
hop: {"pass":2,"hop":1,"ttl":1,"ip":"192.168.0.1","rtt":"3.57"}
hop: {"pass":2,"hop":2,"ttl":2,"ip":"0.0.0.0","rtt":"8.15"}
hop: {"pass":2,"hop":3,"ttl":3,"ip":"64.59.162.189","rtt":"15.62"}
hop: {"pass":2,"hop":4,"ttl":4,"ip":"66.163.68.129","rtt":"16.31"}
hop: {"pass":2,"hop":5,"ttl":5,"ip":"66.163.72.242","rtt":"15.14"}
hop: {"pass":2,"hop":6,"ttl":6,"ip":"66.163.74.158","rtt":"20.59"}
hop: {"pass":2,"hop":7,"ttl":7,"ip":"66.163.75.90","rtt":"40.36"}
hop: {"pass":2,"hop":8,"ttl":8,"ip":"206.223.116.227","rtt":"48.46"}
hop: {"pass":2,"hop":9,"ttl":9,"ip":"114.31.199.248","rtt":"196.28"}
hop: {"pass":2,"hop":10,"ttl":10,"ip":"114.31.199.58","rtt":"202.93"}
hop: {"pass":2,"hop":11,"ttl":11,"ip":"114.31.199.28","rtt":"204.70"}
hop: {"pass":2,"hop":12,"ttl":12,"ip":"175.45.72.93","rtt":"194.45"}
hop: {"pass":2,"hop":13,"ttl":13,"ip":"175.45.108.214","rtt":"198.89"}
hop: {"pass":2,"hop":14,"ttl":14,"ip":"124.47.128.22","rtt":"206.03"}
hop: {"pass":2,"hop":15,"ttl":15,"rtt":-1,"err":"timeout"}
hop: {"pass":2,"hop":16,"ttl":16,"rtt":-1,"err":"timeout"}
hop: {"pass":2,"hop":17,"ttl":17,"rtt":-1,"err":"timeout"}
passed 1034
hop: {"pass":2,"hop":18,"ttl":18,"rtt":-1,"err":"timeout"}
maxhops 24
pass: 1
passed 1271
hop: {"pass":3,"hop":1,"ttl":1,"ip":"192.168.0.1","rtt":"94.22"}
hop: {"pass":3,"hop":2,"ttl":2,"ip":"0.0.0.0","rtt":"102.12"}
passed 1535
hop: {"pass":3,"hop":3,"ttl":3,"ip":"64.59.162.189","rtt":"101.13"}
hop: {"pass":3,"hop":4,"ttl":4,"ip":"66.163.68.129","rtt":"102.31"}
hop: {"pass":3,"hop":5,"ttl":5,"ip":"66.163.72.242","rtt":"101.42"}
passed 1773
hop: {"pass":3,"hop":6,"ttl":6,"ip":"66.163.74.158","rtt":"102.96"}
hop: {"pass":3,"hop":7,"ttl":7,"ip":"66.163.75.90","rtt":"100.11"}
passed 2036
hop: {"pass":3,"hop":8,"ttl":8,"ip":"206.223.116.227","rtt":"101.23"}
passed 2275
hop: {"pass":3,"hop":9,"ttl":9,"ip":"114.31.199.248","rtt":"306.14"}
passed 2537
hop: {"pass":3,"hop":10,"ttl":10,"ip":"114.31.199.58","rtt":"306.20"}
passed 2776
hop: {"pass":3,"hop":11,"ttl":11,"ip":"114.31.199.28","rtt":"306.25"}
passed 3038
exiting due to no client response
logout

[Process completed]

**Comment by agamba** [comment]
Hi Andrew, 
Yesterday, in a previous conversation via email, David explained that initializing the server in a "public" (NODE_ENV=public) mode seems to prevent this issue. I'm running a full test and report shortly.

@David, if this works, is there any particular concern/reason why not running the server in this mode by default? and thus, changing:

https://github.com/ixmaps/ixnode/blob/prerelease/start.sh#L19
From this: 
./node server.js
to 
NODE_ENV=public ./node server.js

And then in oder to launch the server in the browser, modifying
https://github.com/ixmaps/ixnode/blob/prerelease/server.js#L74
By removing the exception:
if (!isPublic)

**Comment by agamba** [comment]
I've completed some tests and identified that the cause of this issue has to do when you move focus from the browse tab displaying the IXmapsClient. As soon as you move the focus the function pingCheck (setInterval function) is triggered, and a few seconds after the server disconnects. 

In my tests by removing check the server never disconnects.

@David, any reason why we should have this function, or why such a short time: 3 secs. (if (passed > 3000))?

https://github.com/ixmaps/ixnode/blob/prerelease/server.js#L118

        if (!isPublic) {
          pingCheck = setInterval(function() {
            var passed = new Date().getTime() - lastResponse.getTime();
            if (passed > 1000) {
              console.log('passed', passed);
            }
            if (passed > 3000) {
              console.log('exiting due to no client response');
              process.exit(0);
            }
          }, 500);
        }

**Comment by Andrew-Clement** [comment]
Thanks Antonio, for tracking this down.  It does indeed look like it would account for the problem, at least in part.

However, on some occasions, as I mentioned in my message, this error occurs even when one keeps the focus exclusively on the browse tab displaying the IXmapsClient.

But perhaps this code would also account for these disconnections simply in the case that it takes longer than 3 sec for a response even without shifting attention away??


On 2015-12-16, at 12:58 PM, Antonio Gamba-Bari <notifications@github.com> wrote:

I've completed some tests and identified that the cause of this issue has to do when you move focus from the browse tab displaying the IXmapsClient. As soon as you move the focus the function pingCheck (setInterval function) is triggered, and a few seconds after the server disconnects.

In my tests by removing check the server never disconnects.

@David, any reason why we should have this function, or why such a short time: 3 secs. (if (passed > 3000))?

https://github.com/ixmaps/ixnode/blob/prerelease/server.js#L118

    if (!isPublic) {
      pingCheck = setInterval(function() {
        var passed = new Date().getTime() - lastResponse.getTime();
        if (passed > 1000) {
          console.log('passed', passed);
        }
        if (passed > 3000) {
          console.log('exiting due to no client response');
          process.exit(0);
        }
      }, 500);
    }

**Comment by vid** [comment]
Hey, I think you found it. I only adjusted it on the client side. Adjusting it on the server side should take care of this problem.

**Comment by vid** [comment]
It's pretty likely that adjusting the server side will fix it, it seems 3
seconds is too short for a moderately under-resourced computer.

David

On 16 December 2015 at 16:49, Andrew-Clement <notifications@github.com>
wrote:

> Thanks Antonio, for tracking this down. It does indeed look like it would
> account for the problem, at least in part.
>
> However, on some occasions, as I mentioned in my message, this error
> occurs even when one keeps the focus exclusively on the browse tab
> displaying the IXmapsClient.
>
> But perhaps this code would also account for these disconnections simply
> in the case that it takes longer than 3 sec for a response even without
> shifting attention away??
>
>
> On 2015-12-16, at 12:58 PM, Antonio Gamba-Bari <notifications@github.com>
> wrote:
>
> I've completed some tests and identified that the cause of this issue has
> to do when you move focus from the browse tab displaying the IXmapsClient.
> As soon as you move the focus the function pingCheck (setInterval function)
> is triggered, and a few seconds after the server disconnects.
>
> In my tests by removing check the server never disconnects.
>
> @David, any reason why we should have this function, or why such a short
> time: 3 secs. (if (passed > 3000))?
>
> https://github.com/ixmaps/ixnode/blob/prerelease/server.js#L118
>
> if (!isPublic) {
> pingCheck = setInterval(function() {
> var passed = new Date().getTime() - lastResponse.getTime();
> if (passed > 1000) {
> console.log('passed', passed);
> }
> if (passed > 3000) {
> console.log('exiting due to no client response');
> process.exit(0);
> }
> }, 500);
> }
> —
> Reply to this email directly or view it on GitHub.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ixmaps/ixnode/issues/55#issuecomment-165253765>.
>



-- 
http://zooid.org/vid

**Comment by agamba** [comment]
Ok, this is great news. I'll do a test increasing the time. However, in a local test I removed the check for time out all together, and in this way the server never attempts to exit, even after hours of inactivity, which might be the expected behaviour.

**Comment by vid** [comment]
The point of the timeout is the user can just close their browser and after
some seconds the server will exit. But it can also be removed, though
setting a long timeout should be fine, if the user's computer has 30 second
delays there's something terminally wrong.

It's important to NOT normally run the server in public mode, since it
would let anyone who can reach the host trigger traces.

On 16 December 2015 at 18:09, Antonio Gamba-Bari <notifications@github.com>
wrote:

> Ok, this is great news. I'll do a test increasing the time. However, in a
> local test I removed the check for time out all together, and in this way
> the server never attempts to exit, even after hours of inactivity, which
> might be the expected behaviour.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ixmaps/ixnode/issues/55#issuecomment-165277819>.
>



-- 
http://zooid.org/vid

**Comment by Andrew-Clement** [comment]
HAsn't this been resolved?? If so, please close.
