### ISSUE TITLE
Change the repository title to IXmaps Client

### ISSUE THREAD

**Issue by dcwalk** [ixmaps/IXmapsClient#60]
Per discussion around readme and repacking the client, we are phasine out the term 'ixnode'

Can we update the repository name to minimize confusion?

**Comment by Andrew-Clement** [comment]
OK with me, but perhaps there are other implications?

**Comment by vid** [comment]
I don't think there's any problem if you use the rename function. The commit history and issues should go along with it.

**Comment by Andrew-Clement** [comment]
Thanks David, good to hear this. Let's go with the name change then.

A.


On 2015-11-28, at 7:36 AM, "David H. Mason" <notifications@github.com> wrote:

I don't think there's any problem if you use the rename function. The commit history and issues should go along with it.

**Comment by dcwalk** [comment]
@agamba will this cause a challenge if it is done on your end? Perhaps you should make the change whenever is the best moment?

**Comment by Andrew-Clement** [comment]
Looks like this has been done, given the header above?? Close?
