### ISSUE TITLE
Windows packaging

### ISSUE THREAD

**Issue by vid** [ixmaps/IXmapsClient#7]

**Comment by agamba** [comment]
In the past I managed to compile the old raw-socket module on win 32 (XP). At this point I don't have setup a win 64bit environment to do the test, but will work on this in the following days and report any issues compiling and running ixnode

**Comment by agamba** [comment]
While checking the options for installing nvm for windows, at
https://github.com/coreybutler/nvm-windows
I noticed something that says  "iojs is merging back with node" (http://blog.nodejs.org/2015/05/15/node-leaders-are-building-an-open-foundation/)

Does this affect our application, not only for windows?

**Comment by vid** [comment]
It's not relevant at this time at all.

**Comment by agamba** [comment]
Reporting here some of the issues I'm getting when compiling on windows 8. It's seems that still don't get the right version of the C++ compiler as the errors reported are related to C++ code syntax. 
I'm trying an update of the C++ compiler and trying again.


C:\nodejs\ixnode-master>node -v
v2.2.1

C:\nodejs\ixnode-master>python -V
Python 2.7.3

C:\nodejs\ixnode-master>npm install -g gulp && npm install && gulp build
C:\Users\anto\AppData\Roaming\npm\gulp -> C:\Users\anto\AppData\Roaming\npm\node
_modules\gulp\bin\gulp.js
gulp@3.9.0 C:\Users\anto\AppData\Roaming\npm\node_modules\gulp
├── pretty-hrtime@1.0.0
├── interpret@0.6.2
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.1.1
├── tildify@1.1.0 (os-homedir@1.0.0)
├── v8flags@2.0.7 (user-home@1.1.1)
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1
.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── semver@4.3.6
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.
1.5)
├── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, beeper@1.1.0, lodash.
_reinterpolate@3.0.0, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, object-a
ssign@3.0.0, replace-ext@0.0.1, vinyl@0.5.0, lodash.template@3.6.1, through2@2.0
.0, multipipe@0.1.2, dateformat@1.0.11)
├── liftoff@2.1.0 (extend@2.0.1, rechoir@0.6.1, flagged-respawn@0.3.1, resolve@1
.1.6, findup-sync@0.2.1)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.2, vinyl@0
.4.6, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)
npm WARN package.json ixnode@0.0.1 license should be a valid SPDX license expres
sion
\
> raw-socket2@1.2.5 install C:\nodejs\ixnode-master\node_modules\raw-socket2
> node-gyp rebuild


C:\nodejs\ixnode-master\node_modules\raw-socket2>if not defined npm_config_node_
gyp (node "C:\iojs.2.2.1\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\n
ode-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  raw.cc
C:\Users\anto\.node-gyp\2.2.1\deps\v8\include\v8.h(3949): error C2332: 'enum' :
 missing tag name [C:\nodejs\ixnode-master\node_modules\raw-socket2\build\raw.v
cxproj]
C:\Users\anto\.node-gyp\2.2.1\deps\v8\include\v8.h(3949): error C2236: unexpect
ed 'class' 'v8::PropertyHandlerFlags'. Did you forget a ';'? [C:\nodejs\ixnode-
master\node_modules\raw-socket2\build\raw.vcxproj]
C:\Users\anto\.node-gyp\2.2.1\deps\v8\include\v8.h(3949): error C3381: 'v8::Pro
pertyHandlerFlags' : assembly access specifiers are only available in code comp
iled with a /clr option [C:\nodejs\ixnode-master\node_modules\raw-socket2\build
\raw.vcxproj]
C:\Users\anto\.node-gyp\2.2.1\deps\v8\include\v8.h(3949): error C4430: missing
type specifier - int assumed. Note: C++ does not support default-int [C:\nodejs
\ixnode-master\node_modules\raw-socket2\build\raw.vcxproj]
C:\Users\anto\.node-gyp\2.2.1\deps\v8\include\v8.h(3949): error C2864: 'v8::Pro
pertyHandlerFlags::kNone' : only static const integral data members can be init
ialized within a class [C:\nodejs\ixnode-master\node_modules\raw-socket2\build\
raw.vcxproj]
C:\Users\anto\.node-gyp\2.2.1\deps\v8\include\v8.h(3949): error C4430: missing
type specifier - int assumed. Note: C++ does not support default-int [C:\nodejs
\ixnode-master\node_modules\raw-socket2\build\raw.vcxproj]
C:\Users\anto\.node-gyp\2.2.1\deps\v8\include\v8.h(3949): error C2864: 'v8::Pro
pertyHandlerFlags::kAllCanRead' : only static const integral data members can b
e initialized within a class [C:\nodejs\ixnode-master\node_modules\raw-socket2\
build\raw.vcxproj]
C:\Users\anto\.node-gyp\2.2.1\deps\v8\include\v8.h(3949): error C2143: syntax e
rror : missing ';' before '}' [C:\nodejs\ixnode-master\node_modules\raw-socket2
\build\raw.vcxproj]
C:\Users\anto\.node-gyp\2.2.1\deps\v8\include\v8.h(3953): error C2039: 'kNone'
: is not a member of 'v8::PropertyHandlerFlags' [C:\nodejs\ixnode-master\node_m
odules\raw-socket2\build\raw.vcxproj]
          C:\Users\anto\.node-gyp\2.2.1\deps\v8\include\v8.h(3949) : see declar
  ation of 'v8::PropertyHandlerFlags'
C:\Users\anto\.node-gyp\2.2.1\deps\v8\include\v8.h(3953): error C2039: 'kNone'
: is not a member of 'v8::PropertyHandlerFlags' [C:\nodejs\ixnode-master\node_m
odules\raw-socket2\build\raw.vcxproj]
          C:\Users\anto\.node-gyp\2.2.1\deps\v8\include\v8.h(3949) : see declar
  ation of 'v8::PropertyHandlerFlags'
C:\Users\anto\.node-gyp\2.2.1\deps\v8\include\v8.h(3981): error C2039: 'kNone'
: is not a member of 'v8::PropertyHandlerFlags' [C:\nodejs\ixnode-master\node_m
odules\raw-socket2\build\raw.vcxproj]
          C:\Users\anto\.node-gyp\2.2.1\deps\v8\include\v8.h(3949) : see declar
  ation of 'v8::PropertyHandlerFlags'
C:\Users\anto\.node-gyp\2.2.1\deps\v8\include\v8.h(3981): error C2039: 'kNone'
: is not a member of 'v8::PropertyHandlerFlags' [C:\nodejs\ixnode-master\node_m
odules\raw-socket2\build\raw.vcxproj]
          C:\Users\anto\.node-gyp\2.2.1\deps\v8\include\v8.h(3949) : see declar
  ation of 'v8::PropertyHandlerFlags'
C:\Users\anto\.node-gyp\2.2.1\deps\v8\include\v8.h(3981): error C2065: 'kNone'
: undeclared identifier [C:\nodejs\ixnode-master\node_modules\raw-socket2\build
\raw.vcxproj]
..\src\raw.cc(577): warning C4344: behavior change: use of explicit template ar
guments results in call to 'v8::Local<T> NanNew<v8::String,char*>(A0)' [C:\node
js\ixnode-master\node_modules\raw-socket2\build\raw.vcxproj]
          with
          [
              T=v8::String,
              A0=char *
          ]
          but the regular function 'v8::Local<T> NanNew(const char *)' is a bet
  ter match
          with
          [
              T=v8::String
          ]
          if you expect 'v8::Local<T> NanNew(const char *)' to be called then y
  ou need to make it an explicit specialization
          with
          [
              T=v8::String
          ]
..\src\raw.cc(603): error C3861: 'bzero': identifier not found [C:\nodejs\ixnod
e-master\node_modules\raw-socket2\build\raw.vcxproj]
..\src\raw.cc(607): error C3861: 'inet_pton': identifier not found [C:\nodejs\i
xnode-master\node_modules\raw-socket2\build\raw.vcxproj]
..\src\raw.cc(614): error C2664: 'setsockopt' : cannot convert parameter 4 from
 'int *' to 'const char *' [C:\nodejs\ixnode-master\node_modules\raw-socket2\bu
ild\raw.vcxproj]
          Types pointed to are unrelated; conversion requires reinterpret_cast,
   C-style cast or function-style cast
 . . .

**Comment by agamba** [comment]
Any ideas of what this could mean:

I've tried various configurations and updates of visual studio C++ compilers and still getting errors.

I'm not sure if it has to do with the version of iojs

**********************
node-gyp configure --msvs_version=2010
**********************

Setting SDK environment relative to C:\Program Files\Microsoft SDKs\Windows\v7.1
\.
Targeting Windows 7 x64 Release

C:\nodejs\raw-socket>cd ..

C:\nodejs>cd ixnode

C:\nodejs\ixnode>node-gyp configure --msvs_version=2010
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.1
gyp info using node@2.2.1 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\anto\\AppData\\Roaming\\npm\\node_modules\\nod
e-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2010',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\nodejs\\ixnode\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\anto\\AppData\\Roaming\\npm\\node_modules\\nod
e-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\anto\\.node-gyp\\2.2.1\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\anto\\.node-gyp\\2.2.1',
gyp info spawn args   '-Dmodule_root_dir=C:\\nodejs\\ixnode',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\nodejs\\ixnode\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: C:\nodejs\ixnode) while trying to load binding.
gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\anto\AppData\Roaming\npm\n
ode_modules\node-gyp\lib\configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:199:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "C:\\iojs.2.2.1\\node.exe" "C:\\Users\\anto\\AppData\\Roaming\\
npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--msvs_version=2010"

gyp ERR! cwd C:\nodejs\ixnode
gyp ERR! node -v v2.2.1
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok

C:\nodejs\ixnode>

**Comment by vid** [comment]
Unfortunately I don't know much about this but it seems like perhaps deleting default node-gyp directories may help: https://github.com/TooTallNate/node-gyp/issues/162

also I'm not sure why you're running it in ixnode since the build should be in node_modules/raw_socket2

what's changed since you were compiling it in Windows a couple months ago?

**Comment by colinmccann** [comment]
Resolved with IXmapsClient 1.1.1 release
