### ISSUE TITLE
Web Client losing connection to Server OS X 10.10.5 & Firefox

### ISSUE THREAD

**Issue by dcwalk** [ixmaps/IXmapsClient#71]
User Report of issue from 2015-12-17 (post launch):

> Tried on OS-X Yosemite. with Firefox. Web client eventually  loses connection with terminal server. …
> While web client is static, the terminal screen still processes entries (for hours). …
> Upon doing a reload of the client on browser, it appears the terminal server restarts from scratch.

**Comment by vid** [comment]
It sounds like we're going to have to disable the fancy timeout stuff since it's causing all these problems.

**Comment by Andrew-Clement** [comment]
It would be good to know what is leading to these disconnections (data overflows?). When making these long runs of TRsets, the disconnection appears to occur much later than those we were having trouble with before. This situation appears to be better than before and I would rather not simply cancel the 'fancy timeout stuff' (not sure what that means). Would it help to turn off some of the detailed data capture? Instrument the generation process differently to capture the relevant factors?   

Until the disconnections can be better understood, perhaps the timeout period can be dialed down to not allow such long Terminal runs after the Client disconnects, and then give users a better, more reassuring indication of what happened and how to recover.

**Comment by agamba** [comment]
A few days ago, I've temporarily disabled the timeout by commenting the
lines described in issue 55 <https://github.com/ixmaps/ixnode/issues/55>.
and updated the packages for Mac OS and Linux at
https://www.ixmaps.ca/contribute.php

David, I've not updated the git repo with the commented these lines yet,
but just to be clear, I presume Dawn is using an old version. As as
Indicated, the code producing the timeout check have been commented in the
packages.

For further testings please re-download and use these versions.

**Comment by dcwalk** [comment]
@agamba this is a report from a user post-launch, I am just relaying here. I haven't tested or replicated this issue.

**Comment by Andrew-Clement** [comment]
I believe this is the same issue I reported from personal experience in issue #69 (if they should be merged, I'm not sure how this is done) I believe the user report that @dcwalk is referring to is this tweet: I presume you're referring to this tweet: https://twitter.com/jfmezei/status/677667118951899136

**Comment by Andrew-Clement** [comment]
Haven't seen any recent evidence of this, so possibly working fine now??  Merge with 69 and close??
