### ISSUE TITLE
add submission of "city" field to ixmaps server

### ISSUE THREAD

**Issue by agamba** [ixmaps/IXmapsClient#73]
I've noticed that although the city is collected in the first screen, it is not being submitted as part of the POST submission.

<img width="879" alt="screen shot 2016-01-25 at 8 26 13 pm" src="https://cloud.githubusercontent.com/assets/999407/12569992/fc049dce-c3a1-11e5-9bb4-132b7a82dec0.png">

**Comment by colinmccann** [comment]
Fixed with php-backend commit on Aug 9, 2020
