### ISSUE TITLE
Mac OS X error 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'

### ISSUE THREAD

**Issue by dcwalk** [ixmaps/IXmapsClient#79]
User reported on twitter that using Mac OS X client leads to the 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' error for the top 25 clients. @agamba any thoughts?

**Comment by Andrew-Clement** [comment]
Antonio, Colin,

Hope you shed any light on this.

I just ran the my IXmapsClient for MacOS on TR Set: 20: top 25 Sites in Canada, and while I didn't replicate the reported error, something is not working properly. All 25 routes report "Insufficient Traceroute responses. (Contribution id: 475XX)"




Would moving to the new server help clear up this SIGNATURE verification issue??

BTW, the summary message reports 25 of 25 successfully contributed, notwithstanding the "Insufficient Traceroute responses" indicator, and none of my routes showing up in the 'Last 50 submitted' Quick Search. Likely a separate, lower priority issue.

best,

Andrew.

PS I'm currently in Vancouver airport (YVR) in transit to Barcelona, so only sporadically connected for the next day or so..


On 2016-08-28, at 8:05 AM, dcwalk <notifications@github.com> wrote:

User reported on twitter that using Mac OS X client leads to the 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' error for the top 25 clients. @agamba any thoughts?

**Comment by valberg** [comment]
I'm getting the same error. Here is the output (I stopped after 8 failures): https://gist.github.com/valberg/58a11b5ff69ac6f0bfd939f25979809b

**Comment by agamba** [comment]
Hello Andrew, valberg. Thank you for reporting this. We have solve this in the new version that will be up on our website very soon. @Andrrew the testing distribution, which is submitting data to the testing server does not present the issue.

**Comment by agamba** [comment]
We have identified that this is occurs due to our outdates SSL certificate in the server. But again, during the testing on our new server we have fixed the issue.

**Comment by Andrrew** [comment]
I think you have the wrong Andrew.  (I don't recognise ixmaps).

AM
