### ISSUE TITLE
Client crashes during generation

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/IXmapsClient#81]
﻿For no apparaent reason, the client produces a Submission error message and stops running. See example image.

Re-running the TRset can get further but then  may crash again.

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/12848029/18950742/a73a2198-8641-11e6-9297-6e8caf0caef7.png)

**Comment by agamba** [comment]
See my response to issue 82 - https://github.com/ixmaps/IXmapsClient/issues/82
This has been fixed in the https://www.iprp.ca/
