### ISSUE TITLE
Need to recover more gacefully from Client crash

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/IXmapsClient#82]
When reporting a submission error (see #81 ), it would be good to provide the user with more of an indication of what went wrong, or at least what she could do to recover.

Currently all one sees is the cryptic: **submission error {}**

If no further navigation is possible at this point, then how about something like:
      **submission error {code} Sorry about that. To continue, you need to close this window and re-launch the traceroute generator**

**Comment by agamba** [comment]
I have identified and fixed the error that was causing this behaviour. With this fix the IXmapsClient will not crash an will display an error message to the user. See image bellow. Please advice in suggestions for the wording of this message. 

<img width="1011" alt="screen shot 2016-10-11 at 1 18 37 pm" src="https://cloud.githubusercontent.com/assets/999407/19281190/04537388-8fb7-11e6-9af5-9df2e715eece.png">

**Comment by Andrew-Clement** [comment]
Good.  

I suggest that the instead of the green **submitted** tag on the left, which is the same as for successful submission of traceroutes and hence possibly misleading, it be yellow, and say 'error'

On the right, instead of 'The error has been saved', it read 'The error has been recorded'
