### ISSUE TITLE
Screensaver appears to pause Client operation

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/IXmapsClient#86]
I friend/neighbour I recruited to test the Cleint (pseudonym blitz, using OS X 10.11.6)  reports that when his screensaver kicks in, the Client stops running. Turning off the screensaver has the Client resume.  It may be worth a note.  

>>>>>>>>>>
From: Ron Krieg <ronkrieg@hotmail.com>
Subject: Re: another bug
Date: 12 December, 2016 4:11:03 PM PST
To: Andrew Clement <andrew.clement@utoronto.ca>

Regarding the second point, the no response to ping are very brief and the client just carries on, no restarting necessary.

From: Andrew Clement <andrew.clement@utoronto.ca>
Sent: December 12, 2016 4:05 PM
To: Ron Krieg
Subject: Re: another bug
 
Thanks Ron, this provides helpful diagnostics. We haven't heard about the screensaver issue and will pass this on.

We have encountered the  "Server Disconnected, the server is not responding to ping requests" issue before. I presume from what you say here is that after some period, it re-connects to the server and continues generating traceroutes. Or do you have to restart the Client?

A.

On 2016-12-12, at 2:47 PM, Ron Krieg <ronkrieg@hotmail.com> wrote:

Hello Andrew

Interesting info.  Regarding the pauses I was referring to, they are not momentary.  As soon as I went out of screensaver things started up again and now that I have shut the screen saver off they have gone away completely.  Its been running fine all afternoon.  What I see with the short pauses you are referring to is a headliner saying "Server Disconnected, the server is not responding to ping requests"  This comes and goes all the time but is very different from the Screensaver issue.  When the screensaver comes on, it stops altogether.  It starts up automatically when I go out of screensaver.

Ron

From: Andrew Clement <andrew.clement@utoronto.ca>
Sent: December 12, 2016 2:10 PM
To: Ron Krieg
Subject: Re: another bug
 
Hi Ron,

How long are the pauses?  The program may appear to be pausing as it is waiting for routers to respond to our queries.  As significant number of routers, at major switching centres are programmed to not respond. Our traceroute generator  makes four attempts with each router along the route, waiting up to 750 ms each time (ie a total of 3 secs for each router). It then targets the next router along the route, doing this up to four times before abandoning the route. While this seldom happens, it is not uncommon for there there to be 3 non-responses in a row, meaning a wait of 9 secs.  A whole route can have more than 4 non-responsive routers in total, so pauses of over 10 secs are easily possible.  Or are you talking about much longer pauses than this?

best,

Andrew.

FYI, you can look at the details of a route, including the timing of various hops,  by clicking on a line in a mapped traceroute.

eg Here is one of your most recent routes: (Note the some of the routers are not accurately located, so the actual route is not this jagged.)
<PastedGraphic-1.png>
<PastedGraphic-2.png>
On 2016-12-12, at 12:02 PM, Ron Krieg <ronkrieg@hotmail.com> wrote:

I am finding that the program keeps pausing on me.  I thought it was the energy saving settings for the disk and display causing it, but not so...it seems to be the screensaver. I have now disabled the screensaver.  I will let you know how it goes.

**Comment by colinmccann** [comment]
Closing for now. Also fyi - best to remove personal emails from public resources like this
