### ISSUE TITLE
Terminal instructions should indicate need fo admin pw 

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/IXmapsClient#88]
While the instructions on the Contribute page mention the need to enter an admin password, this is missing from  the message in the Terminal:

I propose that we add a **short paragraph** at the beginning of the blurb

* IXmapsClient local server                                               *
*                                                                         *
***  You may be asked for a password. If so, enter the administrator password for this machine ***
*                                                                         *
* A new browser window should appear momentarily. If the browser window   *
* doesn't open, please point your browser to http://localhost:2040        *

**Comment by colinmccann** [comment]
Documented in several places now
