### ISSUE TITLE
I would like to test against a comma separated list of domains

### ISSUE THREAD

**Issue by Leopere** [ixmaps/IXmapsClient#89]
I figure if I'm going to submit any data it might as well be a reasonable dataset not just one domain at a time.  Can we be able to submit more than one domain's traceroute at a time?

**Comment by colinmccann** [comment]
A comma separated list is a good. We will look into incorporating that.
One alternative at this point is our pre-generated traceroute sets (trsets). These are listed in detail at https://ixmaps.ca/trsets/ and should be available in the TR Set dropdown for the submission client.
