### ISSUE TITLE
Python error in TRdetails

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/IXmapsClient#95]
![pastedgraphic-14](https://cloud.githubusercontent.com/assets/12848029/24773288/86fa744c-1ae2-11e7-8078-c67a1b60653b.png)
![pastedgraphic-9](https://cloud.githubusercontent.com/assets/12848029/24773295/8c97a064-1ae2-11e7-9c9c-b953c0251ce0.png)
![pastedgraphic-10](https://cloud.githubusercontent.com/assets/12848029/24773303/9371106e-1ae2-11e7-8dc6-d01b89d96713.png)

cd /Applications//IXmapsClient.app/Contents/Resources/ixmaps-darwin/ ; ./start-macos.sh
Last login: Tue Apr  4 20:12:11 on console
Macintosh-272:~ andrewclementAir$ cd /Applications//IXmapsClient.app/Contents/Resources/ixmaps-darwin/ ; ./start-macos.sh

***************************************************************************
* IXmapsClient local server                                               *
*                                                                         *
* A new browser window should appear momentarily. If the browser window   *
* doesn't open, please point your browser to http://localhost:2040        *
*                                                                         *
* This window will remain open in the background, showing communication   *
* between your device and the IXmaps database.                            *
*                                                                         *
* If you don't see the message -IXmapsClient server started-              *
* something has gone wrong. Please visit                                  *
* http://www.ixmaps.ca/contribute for assistance                          *
*                                                                         *
* To terminate IXmapsClient press: control+C, then close this Terminal    *
* window and the browser window.                                          *
*                                                                         *
* To remove IXmapsClient from your device, delete IXmapsClient.app folder.*
*                                                                         *
* Please note that this minimal server requires root access to initiate   *
* traceroute requests. We invite you to inspect the code to verify its    *
* safety and privacy protection.                                          *
*                                                                         *
* For more information on IXmapsClient, please visit:                     *
* http://www.ixmaps.ca                                                    *
* https://github.com/ixmaps/IXmapsClient/                                 *
*                                                                         *
***************************************************************************

IXmapsClient server started at http://127.0.0.1:2040
Development mode: false
Connection
trsets 39
sending prefs { submitter: 'AndrewC',
  city: 'Toronto',
  postal_code: 'M6R 1T1',
  isp: 'Bell Canada' }
sending geoip { ip_address: '138.51.9.72',
  city: 'Toronto',
  region: 'ON',
  country: 'CA',
  postal_code: 'm5s 1c1',
  asn: '239',
  isp: 'University of Toronto',
  lat: 43.6629,
  lon: -79.3987 }
Connection
trsets 39
sending prefs { submitter: 'AndrewC',
  city: 'Toronto',
  postal_code: 'M6R 1T1',
  isp: 'Bell Canada' }
sending geoip { ip_address: '138.51.9.72',
  city: 'Toronto',
  region: 'ON',
  country: 'CA',
  postal_code: 'm5s 1c1',
  asn: '239',
  isp: 'University of Toronto',
  lat: 43.6629,
  lon: -79.3987 }
info: {"submitter":"AndrewC","postal_code":"M6R 1T1","dest":"osap.on.ca","trset":"","queries":4,"timeout":750,"maxhops":24,"raw_protocol":"ICMP","max_sequential_errors":4,"include_platform_traceroute":false,"platform_protocol":"Default","platform_limit_ms":60000,"city":"Toronto","isp":"University of Toronto"}
STATUS: Host osap.on.ca
info: options{
  "submitter": "AndrewC",
  "postal_code": "M6R 1T1",
  "dest": "osap.on.ca",
  "trset": "",
  "queries": 4,
  "timeout": 750,
  "maxhops": 24,
  "raw_protocol": "ICMP",
  "max_sequential_errors": 4,
  "include_platform_traceroute": false,
  "platform_protocol": "Default",
  "platform_limit_ms": 60000,
  "city": "Toronto",
  "isp": "University of Toronto"
}
hop: {"pass":1,"hop":1,"ttl":1,"ip":"10.7.200.7","rtt":"11.91"}
hop: {"pass":1,"hop":2,"ttl":2,"ip":"100.64.16.1","rtt":"26.48"}
hop: {"pass":1,"hop":3,"ttl":3,"ip":"128.100.200.241","rtt":"14.75"}
hop: {"pass":1,"hop":4,"ttl":4,"ip":"128.100.200.244","rtt":"2.92"}
hop: {"pass":1,"hop":5,"ttl":5,"ip":"128.100.200.201","rtt":"13.63"}
hop: {"pass":1,"hop":6,"ttl":6,"ip":"128.100.96.16","rtt":"13.58"}
hop: {"pass":1,"hop":7,"ttl":7,"ip":"205.211.94.241","rtt":"20.54"}
hop: {"pass":1,"hop":8,"ttl":8,"ip":"216.66.30.113","rtt":"33.63"}
hop: {"pass":1,"hop":9,"ttl":9,"ip":"184.105.80.9","rtt":"27.71"}
hop: {"pass":1,"hop":10,"ttl":10,"ip":"72.52.92.165","rtt":"101.84"}
hop: {"pass":1,"hop":11,"ttl":11,"ip":"72.52.92.214","rtt":"99.61"}
hop: {"pass":1,"hop":12,"ttl":12,"rtt":-1,"err":"timeout"}
hop: {"pass":1,"hop":13,"ttl":13,"ip":"31.220.0.199","rtt":"100.64"}
complete pass 1
pass: 0
hop: {"pass":2,"hop":1,"ttl":1,"ip":"10.7.200.7","rtt":"14.32"}
hop: {"pass":2,"hop":2,"ttl":2,"ip":"100.64.16.1","rtt":"9.86"}
hop: {"pass":2,"hop":3,"ttl":3,"ip":"128.100.200.241","rtt":"18.20"}
hop: {"pass":2,"hop":4,"ttl":4,"ip":"128.100.200.244","rtt":"19.01"}
hop: {"pass":2,"hop":5,"ttl":5,"ip":"128.100.200.201","rtt":"2.03"}
hop: {"pass":2,"hop":6,"ttl":6,"ip":"128.100.96.16","rtt":"2.99"}
hop: {"pass":2,"hop":7,"ttl":7,"ip":"205.211.94.241","rtt":"8.29"}
hop: {"pass":2,"hop":8,"ttl":8,"ip":"216.66.30.113","rtt":"14.66"}
hop: {"pass":2,"hop":9,"ttl":9,"ip":"184.105.80.9","rtt":"20.79"}
hop: {"pass":2,"hop":10,"ttl":10,"ip":"72.52.92.165","rtt":"101.46"}
hop: {"pass":2,"hop":11,"ttl":11,"ip":"72.52.92.214","rtt":"101.04"}
hop: {"pass":2,"hop":12,"ttl":12,"ip":"128.100.200.244","rtt":"10.74"}
hop: {"pass":2,"hop":13,"ttl":13,"ip":"128.100.200.244","rtt":"5.97"}
hop: {"pass":2,"hop":14,"ttl":14,"ip":"128.100.200.244","rtt":"16.73"}
hop: {"pass":2,"hop":15,"ttl":15,"ip":"128.100.200.244","rtt":"30.21"}
hop: {"pass":2,"hop":16,"ttl":16,"ip":"128.100.200.244","rtt":"5.47"}
hop: {"pass":2,"hop":17,"ttl":17,"ip":"128.100.200.244","rtt":"6.07"}
hop: {"pass":2,"hop":18,"ttl":18,"ip":"128.100.200.244","rtt":"1.65"}
hop: {"pass":2,"hop":19,"ttl":19,"ip":"128.100.200.244","rtt":"9.47"}
hop: {"pass":2,"hop":20,"ttl":20,"ip":"128.100.200.244","rtt":"7.29"}
hop: {"pass":2,"hop":21,"ttl":21,"ip":"128.100.200.244","rtt":"5.16"}
hop: {"pass":2,"hop":22,"ttl":22,"ip":"128.100.200.244","rtt":"8.37"}
hop: {"pass":2,"hop":23,"ttl":23,"ip":"128.100.200.244","rtt":"8.81"}
hop: {"pass":2,"hop":24,"ttl":24,"ip":"128.100.200.244","rtt":"6.58"}
maxhops 24
pass: 1
hop: {"pass":3,"hop":1,"ttl":1,"ip":"10.7.200.7","rtt":"32.05"}
hop: {"pass":3,"hop":2,"ttl":2,"ip":"100.64.16.1","rtt":"12.29"}
hop: {"pass":3,"hop":3,"ttl":3,"ip":"128.100.200.241","rtt":"32.38"}
hop: {"pass":3,"hop":4,"ttl":4,"ip":"128.100.200.244","rtt":"8.26"}
hop: {"pass":3,"hop":5,"ttl":5,"ip":"128.100.200.244","rtt":"1.88"}
hop: {"pass":3,"hop":6,"ttl":6,"ip":"128.100.96.16","rtt":"10.21"}
hop: {"pass":3,"hop":7,"ttl":7,"ip":"128.100.200.244","rtt":"18.55"}
hop: {"pass":3,"hop":8,"ttl":8,"ip":"128.100.200.244","rtt":"1.65"}
hop: {"pass":3,"hop":9,"ttl":9,"ip":"128.100.200.244","rtt":"1.73"}
hop: {"pass":3,"hop":10,"ttl":10,"ip":"128.100.200.244","rtt":"2.10"}
hop: {"pass":3,"hop":11,"ttl":11,"ip":"128.100.200.244","rtt":"1.65"}
hop: {"pass":3,"hop":12,"ttl":12,"ip":"128.100.200.244","rtt":"1.49"}
hop: {"pass":3,"hop":13,"ttl":13,"ip":"128.100.200.244","rtt":"25.07"}
hop: {"pass":3,"hop":14,"ttl":14,"ip":"128.100.200.244","rtt":"3.07"}
hop: {"pass":3,"hop":15,"ttl":15,"ip":"128.100.200.244","rtt":"1.66"}
hop: {"pass":3,"hop":16,"ttl":16,"ip":"128.100.200.244","rtt":"2.26"}
hop: {"pass":3,"hop":17,"ttl":17,"ip":"128.100.200.244","rtt":"22.97"}
hop: {"pass":3,"hop":18,"ttl":18,"ip":"128.100.200.244","rtt":"5.03"}
hop: {"pass":3,"hop":19,"ttl":19,"ip":"128.100.200.244","rtt":"17.82"}
hop: {"pass":3,"hop":20,"ttl":20,"ip":"128.100.200.244","rtt":"9.69"}
hop: {"pass":3,"hop":21,"ttl":21,"ip":"128.100.200.244","rtt":"2.73"}
hop: {"pass":3,"hop":22,"ttl":22,"ip":"128.100.200.244","rtt":"11.65"}
hop: {"pass":3,"hop":23,"ttl":23,"ip":"128.100.200.244","rtt":"10.36"}
hop: {"pass":3,"hop":24,"ttl":24,"ip":"128.100.200.244","rtt":"54.17"}
maxhops 24
pass: 2
hop: {"pass":4,"hop":1,"ttl":1,"ip":"10.7.200.7","rtt":"5.79"}
hop: {"pass":4,"hop":2,"ttl":2,"ip":"100.64.16.1","rtt":"1.50"}
hop: {"pass":4,"hop":3,"ttl":3,"ip":"128.100.200.241","rtt":"2.12"}
hop: {"pass":4,"hop":4,"ttl":4,"ip":"128.100.200.244","rtt":"9.29"}
hop: {"pass":4,"hop":5,"ttl":5,"ip":"128.100.200.201","rtt":"8.61"}
hop: {"pass":4,"hop":6,"ttl":6,"ip":"128.100.200.244","rtt":"1.82"}
hop: {"pass":4,"hop":7,"ttl":7,"ip":"128.100.200.244","rtt":"3.54"}
hop: {"pass":4,"hop":8,"ttl":8,"ip":"128.100.200.244","rtt":"1.57"}
hop: {"pass":4,"hop":9,"ttl":9,"ip":"128.100.200.244","rtt":"1.72"}
hop: {"pass":4,"hop":10,"ttl":10,"ip":"128.100.200.244","rtt":"1.69"}
hop: {"pass":4,"hop":11,"ttl":11,"ip":"128.100.200.244","rtt":"17.20"}
hop: {"pass":4,"hop":12,"ttl":12,"rtt":-1,"err":"timeout"}
hop: {"pass":4,"hop":13,"ttl":13,"ip":"31.220.0.199","rtt":"93.99"}
complete pass 4
pass: 3
done: 4 queries
SUBMITTRACE post {
  "timeout": 750,
  "queries": 4,
  "dest": "osap.on.ca",
  "dest_ip": "31.220.0.199",
  "submitter": "AndrewC",
  "city": "Toronto",
  "postal_code": "M6R 1T1",
  "maxhops": 24,
  "os": "Darwin",
  "traceroute_submissions": [
    {
      "client": "IXmapsClient 1.0.6",
      "protocol": "ICMP",
      "tr_data": [
        [
          {
            "pass": 1,
            "hop": 1,
            "ttl": 1,
            "ip": "10.7.200.7",
            "rtt": "11.91"
          },
          {
            "pass": 1,
            "hop": 2,
            "ttl": 2,
            "ip": "100.64.16.1",
            "rtt": "26.48"
          },
          {
            "pass": 1,
            "hop": 3,
            "ttl": 3,
            "ip": "128.100.200.241",
            "rtt": "14.75"
          },
          {
            "pass": 1,
            "hop": 4,
            "ttl": 4,
            "ip": "128.100.200.244",
            "rtt": "2.92"
          },
          {
            "pass": 1,
            "hop": 5,
            "ttl": 5,
            "ip": "128.100.200.201",
            "rtt": "13.63"
          },
          {
            "pass": 1,
            "hop": 6,
            "ttl": 6,
            "ip": "128.100.96.16",
            "rtt": "13.58"
          },
          {
            "pass": 1,
            "hop": 7,
            "ttl": 7,
            "ip": "205.211.94.241",
            "rtt": "20.54"
          },
          {
            "pass": 1,
            "hop": 8,
            "ttl": 8,
            "ip": "216.66.30.113",
            "rtt": "33.63"
          },
          {
            "pass": 1,
            "hop": 9,
            "ttl": 9,
            "ip": "184.105.80.9",
            "rtt": "27.71"
          },
          {
            "pass": 1,
            "hop": 10,
            "ttl": 10,
            "ip": "72.52.92.165",
            "rtt": "101.84"
          },
          {
            "pass": 1,
            "hop": 11,
            "ttl": 11,
            "ip": "72.52.92.214",
            "rtt": "99.61"
          },
          {
            "pass": 1,
            "hop": 12,
            "ttl": 12,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 1,
            "hop": 13,
            "ttl": 13,
            "ip": "31.220.0.199",
            "rtt": "100.64"
          }
        ],
        [
          {
            "pass": 2,
            "hop": 1,
            "ttl": 1,
            "ip": "10.7.200.7",
            "rtt": "14.32"
          },
          {
            "pass": 2,
            "hop": 2,
            "ttl": 2,
            "ip": "100.64.16.1",
            "rtt": "9.86"
          },
          {
            "pass": 2,
            "hop": 3,
            "ttl": 3,
            "ip": "128.100.200.241",
            "rtt": "18.20"
          },
          {
            "pass": 2,
            "hop": 4,
            "ttl": 4,
            "ip": "128.100.200.244",
            "rtt": "19.01"
          },
          {
            "pass": 2,
            "hop": 5,
            "ttl": 5,
            "ip": "128.100.200.201",
            "rtt": "2.03"
          },
          {
            "pass": 2,
            "hop": 6,
            "ttl": 6,
            "ip": "128.100.96.16",
            "rtt": "2.99"
          },
          {
            "pass": 2,
            "hop": 7,
            "ttl": 7,
            "ip": "205.211.94.241",
            "rtt": "8.29"
          },
          {
            "pass": 2,
            "hop": 8,
            "ttl": 8,
            "ip": "216.66.30.113",
            "rtt": "14.66"
          },
          {
            "pass": 2,
            "hop": 9,
            "ttl": 9,
            "ip": "184.105.80.9",
            "rtt": "20.79"
          },
          {
            "pass": 2,
            "hop": 10,
            "ttl": 10,
            "ip": "72.52.92.165",
            "rtt": "101.46"
          },
          {
            "pass": 2,
            "hop": 11,
            "ttl": 11,
            "ip": "72.52.92.214",
            "rtt": "101.04"
          },
          {
            "pass": 2,
            "hop": 12,
            "ttl": 12,
            "ip": "128.100.200.244",
            "rtt": "10.74"
          },
          {
            "pass": 2,
            "hop": 13,
            "ttl": 13,
            "ip": "128.100.200.244",
            "rtt": "5.97"
          },
          {
            "pass": 2,
            "hop": 14,
            "ttl": 14,
            "ip": "128.100.200.244",
            "rtt": "16.73"
          },
          {
            "pass": 2,
            "hop": 15,
            "ttl": 15,
            "ip": "128.100.200.244",
            "rtt": "30.21"
          },
          {
            "pass": 2,
            "hop": 16,
            "ttl": 16,
            "ip": "128.100.200.244",
            "rtt": "5.47"
          },
          {
            "pass": 2,
            "hop": 17,
            "ttl": 17,
            "ip": "128.100.200.244",
            "rtt": "6.07"
          },
          {
            "pass": 2,
            "hop": 18,
            "ttl": 18,
            "ip": "128.100.200.244",
            "rtt": "1.65"
          },
          {
            "pass": 2,
            "hop": 19,
            "ttl": 19,
            "ip": "128.100.200.244",
            "rtt": "9.47"
          },
          {
            "pass": 2,
            "hop": 20,
            "ttl": 20,
            "ip": "128.100.200.244",
            "rtt": "7.29"
          },
          {
            "pass": 2,
            "hop": 21,
            "ttl": 21,
            "ip": "128.100.200.244",
            "rtt": "5.16"
          },
          {
            "pass": 2,
            "hop": 22,
            "ttl": 22,
            "ip": "128.100.200.244",
            "rtt": "8.37"
          },
          {
            "pass": 2,
            "hop": 23,
            "ttl": 23,
            "ip": "128.100.200.244",
            "rtt": "8.81"
          },
          {
            "pass": 2,
            "hop": 24,
            "ttl": 24,
            "ip": "128.100.200.244",
            "rtt": "6.58"
          }
        ],
        [
          {
            "pass": 3,
            "hop": 1,
            "ttl": 1,
            "ip": "10.7.200.7",
            "rtt": "32.05"
          },
          {
            "pass": 3,
            "hop": 2,
            "ttl": 2,
            "ip": "100.64.16.1",
            "rtt": "12.29"
          },
          {
            "pass": 3,
            "hop": 3,
            "ttl": 3,
            "ip": "128.100.200.241",
            "rtt": "32.38"
          },
          {
            "pass": 3,
            "hop": 4,
            "ttl": 4,
            "ip": "128.100.200.244",
            "rtt": "8.26"
          },
          {
            "pass": 3,
            "hop": 5,
            "ttl": 5,
            "ip": "128.100.200.244",
            "rtt": "1.88"
          },
          {
            "pass": 3,
            "hop": 6,
            "ttl": 6,
            "ip": "128.100.96.16",
            "rtt": "10.21"
          },
          {
            "pass": 3,
            "hop": 7,
            "ttl": 7,
            "ip": "128.100.200.244",
            "rtt": "18.55"
          },
          {
            "pass": 3,
            "hop": 8,
            "ttl": 8,
            "ip": "128.100.200.244",
            "rtt": "1.65"
          },
          {
            "pass": 3,
            "hop": 9,
            "ttl": 9,
            "ip": "128.100.200.244",
            "rtt": "1.73"
          },
          {
            "pass": 3,
            "hop": 10,
            "ttl": 10,
            "ip": "128.100.200.244",
            "rtt": "2.10"
          },
          {
            "pass": 3,
            "hop": 11,
            "ttl": 11,
            "ip": "128.100.200.244",
            "rtt": "1.65"
          },
          {
            "pass": 3,
            "hop": 12,
            "ttl": 12,
            "ip": "128.100.200.244",
            "rtt": "1.49"
          },
          {
            "pass": 3,
            "hop": 13,
            "ttl": 13,
            "ip": "128.100.200.244",
            "rtt": "25.07"
          },
          {
            "pass": 3,
            "hop": 14,
            "ttl": 14,
            "ip": "128.100.200.244",
            "rtt": "3.07"
          },
          {
            "pass": 3,
            "hop": 15,
            "ttl": 15,
            "ip": "128.100.200.244",
            "rtt": "1.66"
          },
          {
            "pass": 3,
            "hop": 16,
            "ttl": 16,
            "ip": "128.100.200.244",
            "rtt": "2.26"
          },
          {
            "pass": 3,
            "hop": 17,
            "ttl": 17,
            "ip": "128.100.200.244",
            "rtt": "22.97"
          },
          {
            "pass": 3,
            "hop": 18,
            "ttl": 18,
            "ip": "128.100.200.244",
            "rtt": "5.03"
          },
          {
            "pass": 3,
            "hop": 19,
            "ttl": 19,
            "ip": "128.100.200.244",
            "rtt": "17.82"
          },
          {
            "pass": 3,
            "hop": 20,
            "ttl": 20,
            "ip": "128.100.200.244",
            "rtt": "9.69"
          },
          {
            "pass": 3,
            "hop": 21,
            "ttl": 21,
            "ip": "128.100.200.244",
            "rtt": "2.73"
          },
          {
            "pass": 3,
            "hop": 22,
            "ttl": 22,
            "ip": "128.100.200.244",
            "rtt": "11.65"
          },
          {
            "pass": 3,
            "hop": 23,
            "ttl": 23,
            "ip": "128.100.200.244",
            "rtt": "10.36"
          },
          {
            "pass": 3,
            "hop": 24,
            "ttl": 24,
            "ip": "128.100.200.244",
            "rtt": "54.17"
          }
        ],
        [
          {
            "pass": 4,
            "hop": 1,
            "ttl": 1,
            "ip": "10.7.200.7",
            "rtt": "5.79"
          },
          {
            "pass": 4,
            "hop": 2,
            "ttl": 2,
            "ip": "100.64.16.1",
            "rtt": "1.50"
          },
          {
            "pass": 4,
            "hop": 3,
            "ttl": 3,
            "ip": "128.100.200.241",
            "rtt": "2.12"
          },
          {
            "pass": 4,
            "hop": 4,
            "ttl": 4,
            "ip": "128.100.200.244",
            "rtt": "9.29"
          },
          {
            "pass": 4,
            "hop": 5,
            "ttl": 5,
            "ip": "128.100.200.201",
            "rtt": "8.61"
          },
          {
            "pass": 4,
            "hop": 6,
            "ttl": 6,
            "ip": "128.100.200.244",
            "rtt": "1.82"
          },
          {
            "pass": 4,
            "hop": 7,
            "ttl": 7,
            "ip": "128.100.200.244",
            "rtt": "3.54"
          },
          {
            "pass": 4,
            "hop": 8,
            "ttl": 8,
            "ip": "128.100.200.244",
            "rtt": "1.57"
          },
          {
            "pass": 4,
            "hop": 9,
            "ttl": 9,
            "ip": "128.100.200.244",
            "rtt": "1.72"
          },
          {
            "pass": 4,
            "hop": 10,
            "ttl": 10,
            "ip": "128.100.200.244",
            "rtt": "1.69"
          },
          {
            "pass": 4,
            "hop": 11,
            "ttl": 11,
            "ip": "128.100.200.244",
            "rtt": "17.20"
          },
          {
            "pass": 4,
            "hop": 12,
            "ttl": 12,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 4,
            "hop": 13,
            "ttl": 13,
            "ip": "31.220.0.199",
            "rtt": "93.99"
          }
        ]
      ],
      "result": "completed"
    }
  ]
}
submitted: Processed osap.on.ca (31.220.0.199) - TRID 704804
info: done host osap.on.ca
STATUS: done

**Comment by agamba** [comment]
I've inspected this case and discovered that the ip 100.64.16.1 was the first non-private ip. However MM does not find any data for this ip and this results in latitude and coordinates set to null values. Correcting this coordinates (i.e. equal to zero) fixed the error page in TR details.

**Comment by Andrew-Clement** [comment]
Good. I hope you also corrected the code so that other IPs that MM cannot find won't produce the same error. 

This suggests that we need include these situations in tackling the the first hop issue.

**Comment by Andrew-Clement** [comment]
I see that 100.64.16.0 has not been assigned by IANA to an AS, but is simply reserved for internal use.  So I wonder why this appears here as "the first non-private ip". My understanding is that the TR should start with the next router ie 128.100.200.241, which is a UofT router.  This suggests a continuing bug in the code.

From whois.arin.net:

You searched for: 100.64.16.0

Network
Net Range	100.64.0.0 - 100.127.255.255
CIDR	100.64.0.0/10
Name	SHARED-ADDRESS-SPACE-RFCTBD-IANA-RESERVED
Handle	NET-100-64-0-0-1
Parent	NET100 (NET-100-0-0-0-0)
Net Type	IANA Special Use
Origin AS	
Organization	Internet Assigned Numbers Authority (IANA)
Registration Date	2012-03-13
Last Updated	2016-04-11
Comments	This block is used as Shared Address Space. Traffic from these addresses does not come from IANA. IANA has simply reserved these numbers in its database and does not use or operate them. We are not the source of activity you may see on logs or in e-mail records. Please refer to https://www.iana.org/abuse/

**Comment by colinmccann** [comment]
We can close this, as my no longer use the cgis
