### ISSUE TITLE
Spurious lodeanto contributions

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/IXmapsClient#99]
@Anto Unless you have been surprisingly peripatetic, there are TRs being submitted erroneously in your name. 

![pastedgraphic-25](https://cloud.githubusercontent.com/assets/12848029/25724291/4ec5c096-30d0-11e7-82e3-5f43c73cdfae.png)
Here's an indication that your name location remains in some default name for the Client
![pastedgraphic-26](https://cloud.githubusercontent.com/assets/12848029/25724487/f95e1738-30d0-11e7-977f-7ba54438e495.png)

**Comment by anto** [comment]
Hi Andrew,

I have no clue on this project as I am not even using it let alone contributing. So I am not sure why you contacted me. I hope it was just a typo.

Cheers,

Anto

**Comment by Andrew-Clement** [comment]
OOppss sorry about that. A typo indeed.  I was aiming this at another Anto @agamba

**Comment by colinmccann** [comment]
This is resolved in v1.1.1
